name: Build website

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: docker://pandoc/core:2.14
      options: --entrypoint=sh
    steps:

      - name: Install dependencies
        run: apk add git make m4

      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Build
        run: make

      - name: Copy custom domain name configuration
        run: cp CNAME output/public/

      - name: Store generated content
        uses: actions/upload-artifact@v3
        with:
          path: output/public
          name: website

      - name: Prepare tarball for native GH pages
        run: tar cvf artifact.tar -C output/public .

      - name: Store generated content as tarball for GH pages
        # actions/upload-pages-artifact is broken with tar --hard-dereference
        uses: actions/upload-artifact@v3
        with:
          path: artifact.tar
          name: github-pages

  deploy:
    needs: build
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
